export function loadSyntheticDashboardData() {
  return {
    jobs: [],
    visits: [],
    findings: [
      {
        id: "demo-finding-1",
        provider_name: "ALI SALEHPOUR MD DDS",
        finding_type: "possible_credit",
        severity: "attention",
        status: "open",
        title: "ALI SALEHPOUR MD DDS",
        summary: "Confirmed by you: HSA paid 275.00 for 2026-02-18, but the claim says you owe 125.00.",
        details: {
          provider_name: "ALI SALEHPOUR MD DDS",
          claim_provider_name: "Provider to confirm",
          service_date: "2026-02-18",
          paid_amount: "275.00",
          responsibility_amount: "125.00",
          credit_amount: "150.00",
          payment_date: "2026-02-19",
          payment_source: "Withdrawal",
          payment_provider_name: "ALI SALEHPOUR MD DDS",
          confirmation_source: "Confirmed by you",
          source_files: ["oweme-synthetic-claims.csv", "oweme-synthetic-hsa-transactions.csv"],
        },
      },
      {
        id: "demo-finding-2",
        provider_name: "ALI SALEHPOUR MD DDS",
        finding_type: "possible_credit",
        severity: "attention",
        status: "open",
        title: "ALI SALEHPOUR MD DDS",
        summary: "Confirmed by you: HSA paid 1079.10 for 2026-02-27, but the claim says you owe 605.20.",
        details: {
          provider_name: "ALI SALEHPOUR MD DDS",
          claim_provider_name: "Provider to confirm",
          service_date: "2026-02-27",
          paid_amount: "1079.10",
          responsibility_amount: "605.20",
          credit_amount: "473.90",
          payment_date: "2026-03-04",
          payment_source: "Withdrawal",
          payment_provider_name: "ALI SALEHPOUR MD DDS",
          confirmation_source: "Confirmed by you",
          source_files: ["oweme-synthetic-claims.csv", "oweme-synthetic-hsa-transactions.csv"],
        },
      },
      {
        id: "demo-finding-3",
        provider_name: "Stone Creek Village De",
        finding_type: "allocation_unclear",
        severity: "attention",
        status: "open",
        title: "Stone Creek Village De",
        summary: "Confirmed by you: Apple Card paid 275.00 for 2026-05-13, but the claim says you owe 12.40.",
        details: {
          provider_name: "Stone Creek Village De",
          claim_provider_name: "Stone Creek Village De",
          service_date: "2026-05-13",
          paid_amount: "275.00",
          responsibility_amount: "12.40",
          credit_amount: "262.60",
          payment_date: "2026-05-14",
          payment_source: "Apple Card",
          payment_provider_name: "Stone Creek Village De",
          payment_method: "Apple Card",
          confirmation_source: "Needs review",
          source_files: ["ClaimResults.xlsx", "HSATransactionsAsOf_07032026.csv"],
        },
      },
      {
        id: "demo-finding-4",
        provider_name: "JAMES D KIM",
        finding_type: "allocation_unclear",
        severity: "attention",
        status: "open",
        title: "JAMES D KIM",
        summary: "Claim from 2026-05-13 shows 12.40 patient responsibility, but no matching payment was found yet.",
        details: {
          provider_name: "JAMES D KIM",
          service_date: "2026-05-13",
          responsibility_amount: "12.40",
          source_files: ["oweme-synthetic-claims.csv"],
          candidate_payments: [],
        },
      },
      {
        id: "demo-finding-5",
        provider_name: "QUEST DIAGNOSTICS",
        finding_type: "allocation_unclear",
        severity: "attention",
        status: "open",
        title: "QUEST DIAGNOSTICS",
        summary: "Claim from 2026-05-08 shows 32.40 patient responsibility, but no matching payment was found yet.",
        details: {
          provider_name: "QUEST DIAGNOSTICS",
          service_date: "2026-05-08",
          responsibility_amount: "32.40",
          source_files: ["oweme-synthetic-claims.csv"],
          candidate_payments: [],
        },
      },
      {
        id: "demo-finding-6",
        provider_name: "Medical payment",
        finding_type: "unassigned_medical_payment",
        severity: "attention",
        status: "open",
        title: "Medical payment",
        summary: "Found $142.00 medical payment on 2026-06-20, but the bank statement does not identify the provider.",
        details: {
          provider_name: "Medical payment",
          payment_date: "2026-06-20",
          paid_amount: "142.00",
          payment_source: "Purchase",
          source_files: ["oweme-synthetic-apple-card.csv"],
          possible_claims: [
            {
              provider_name: "JAMES D KIM",
              service_date: "2026-05-13",
              responsibility_amount: "12.40",
            },
            {
              provider_name: "QUEST DIAGNOSTICS",
              service_date: "2026-05-08",
              responsibility_amount: "32.40",
            },
          ],
        },
      },
    ],
  };
}
